- name: Install yum Utils
  yum:
    name: "yum-utils"
    state: "present"
  become: true
- name: Add Docker Centos Repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: true
- name: Install Docker CE
  shell: yum install -y docker-ce
  become: true
- name: Install Docker Compose
  command: yum -y install docker-compose
  become: true
- name: Enable and Start Docker Daemon
  service: name=docker state=started enabled=yes
- name: Run Portainer Container
  shell: docker run -d --restart unless-stopped -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
- name: Run MailHog Container
  shell: docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
